name: test_shell
on: [push]
jobs:
 check-bats-version:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run Test
      run: ./test_gcd.sh
